export const ResponseStatus = {
    HTTP_OK: 200,
    HTTP_CREATED: 201,
    HTTP_NO_CONTENT: 204,
    HTTP_BAD_REQUEST: 400,
    HTTP_UNAUTHORIZED: 401,
    HTTP_FORBIDDEN: 403,
    HTTP_NOT_FOUND: 404,
    HTTP_IM_A_TEAPOT: 418,
    HTTP_TOO_MANY_REQUESTS: 429,
    HTTP_INTERNAL_SERVER_ERROR: 500
};
